/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.*;
import Controller.ctlEmpleado;
import Controller.ctlProducto;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class frmSolFitness extends javax.swing.JFrame {
    
    
    ctlProducto ctlProducto;
    ctlEmpleado ctlEmpleado;
    LinkedList<clsEmpleado> empleadoObjectList = new LinkedList();
    LinkedList<clsProducto> productoObjectList = new LinkedList();
    /**
     * Creates new form frmSolFitness
     */
    public frmSolFitness() {
        initComponents();
        this.ctlProducto = new ctlProducto();
        this.ctlEmpleado = new ctlEmpleado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        listaEmpleados = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtUsuarioAcesso = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtContraseñaAcceso = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoEmpleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCargoEmpleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDocumentoIdentidadEmpleado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCorreoElectronicoEmpleado = new javax.swing.JTextField();
        btnCreateEmpleado = new javax.swing.JButton();
        btnSelectEmpleado = new javax.swing.JButton();
        btnUpdateEmpleado = new javax.swing.JButton();
        btnDeleteEmpleado = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtApellidoCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDocumentoIdentidadCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCorreoElectronicoCliente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDireccionCliente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        btnCreateCliente = new javax.swing.JButton();
        btnSelectCliente = new javax.swing.JButton();
        btnUpdateCliente = new javax.swing.JButton();
        btnDeleteCliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtReferenciaProducto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        btnCreateproducto = new javax.swing.JButton();
        btnSelectProducto = new javax.swing.JButton();
        btnUpadteProducto = new javax.swing.JButton();
        btnDeleteProducto = new javax.swing.JButton();
        cbTallaProducto = new javax.swing.JComboBox<>();
        cbColorProducto = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtIdVentas = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtReferenciaProductoVentas = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtIdClienteVentas = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtIdEmpleadoVentas = new javax.swing.JTextField();
        btnCreateVentas = new javax.swing.JButton();
        btnSelectVentas = new javax.swing.JButton();
        btnUpdateVentas = new javax.swing.JButton();
        btnDeleteVentas = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        txtCantidadVentas = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        listaEmpleado = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        txtIdFacturacion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaFacturacion = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        txtTotalFactura = new javax.swing.JTextField();
        btnCrearFactura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        listaEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaEmpleados.setName(""); // NOI18N

        jLabel25.setText("Usuario");

        jLabel26.setText("Contraseña");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContraseñaAcceso))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(34, 34, 34)
                        .addComponent(txtUsuarioAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsuarioAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(txtContraseñaAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        listaEmpleados.addTab("Acceso", jPanel6);

        jPanel1.setEnabled(false);

        listaProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Producto 1", "Producto 2", "Producto 3", "Producto 4", "Producto 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaProductos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        listaEmpleados.addTab("Lista Productos", jPanel1);

        jLabel2.setText("Id");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Cargo");

        jLabel6.setText("Documento Identidad");

        jLabel7.setText("Correo electrónico");

        btnCreateEmpleado.setText("Create");
        btnCreateEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEmpleadoActionPerformed(evt);
            }
        });

        btnSelectEmpleado.setText("Select");
        btnSelectEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectEmpleadoActionPerformed(evt);
            }
        });

        btnUpdateEmpleado.setText("Update");
        btnUpdateEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEmpleadoActionPerformed(evt);
            }
        });

        btnDeleteEmpleado.setText("Delete");
        btnDeleteEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtIdEmpleado))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtApellidoEmpleado)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnCreateEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCargoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(txtDocumentoIdentidadEmpleado)
                            .addComponent(txtCorreoElectronicoEmpleado))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnSelectEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(btnUpdateEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnDeleteEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCargoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtDocumentoIdentidadEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCorreoElectronicoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateEmpleado)
                    .addComponent(btnSelectEmpleado)
                    .addComponent(btnUpdateEmpleado)
                    .addComponent(btnDeleteEmpleado))
                .addGap(33, 33, 33))
        );

        listaEmpleados.addTab("Empleado", jPanel2);

        jLabel9.setText("Id");

        jLabel10.setText("Nombre");

        jLabel11.setText("Apellido");

        jLabel12.setText("Documento Identidad");

        jLabel13.setText("Correo electrónico");

        jLabel14.setText("Dirección");

        jLabel15.setText("Teléfono");

        btnCreateCliente.setText("Create");

        btnSelectCliente.setText("Select");

        btnUpdateCliente.setText("Update");

        btnDeleteCliente.setText("Delete");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdCliente))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoCliente)
                            .addComponent(txtTelefonoCliente))))
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDocumentoIdentidadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(txtCorreoElectronicoCliente)
                    .addComponent(txtDireccionCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnCreateCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSelectCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdateCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnDeleteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtDocumentoIdentidadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtCorreoElectronicoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateCliente)
                    .addComponent(btnSelectCliente)
                    .addComponent(btnUpdateCliente)
                    .addComponent(btnDeleteCliente))
                .addContainerGap())
        );

        listaEmpleados.addTab("Cliente", jPanel3);

        jLabel16.setText("Referencia");

        jLabel17.setText("Nombre");

        jLabel18.setText("Talla");

        jLabel19.setText("Color");

        jLabel20.setText("Precio");

        btnCreateproducto.setText("Create");
        btnCreateproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateproductoActionPerformed(evt);
            }
        });

        btnSelectProducto.setText("Select");
        btnSelectProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectProductoActionPerformed(evt);
            }
        });

        btnUpadteProducto.setText("Update");
        btnUpadteProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpadteProductoActionPerformed(evt);
            }
        });

        btnDeleteProducto.setText("Delete");
        btnDeleteProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductoActionPerformed(evt);
            }
        });

        cbTallaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS", "S", "M", "L", "XL" }));

        cbColorProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Gris", "Blanco", "Azul", "Rosado", "Morado", "Rojo" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtReferenciaProducto)
                            .addComponent(txtNombreProducto)
                            .addComponent(cbTallaProducto, 0, 99, Short.MAX_VALUE))
                        .addGap(129, 129, 129)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbColorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnCreateproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnSelectProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(btnUpadteProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnDeleteProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtReferenciaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(cbColorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(cbTallaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateproducto)
                    .addComponent(btnSelectProducto)
                    .addComponent(btnUpadteProducto)
                    .addComponent(btnDeleteProducto))
                .addGap(33, 33, 33))
        );

        listaEmpleados.addTab("Producto", jPanel4);

        jLabel21.setText("Id");

        jLabel22.setText("Referencia producto");

        jLabel23.setText("Id cliente");

        jLabel24.setText("Id empleado");

        btnCreateVentas.setText("Create");

        btnSelectVentas.setText("Select");

        btnUpdateVentas.setText("Update");
        btnUpdateVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVentasActionPerformed(evt);
            }
        });

        btnDeleteVentas.setText("Delete");

        jLabel27.setText("Cantidad");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdVentas))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdEmpleadoVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(txtIdClienteVentas)
                            .addComponent(txtReferenciaProductoVentas))))
                .addGap(90, 90, 90)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnCreateVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnSelectVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnUpdateVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnDeleteVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtIdVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtCantidadVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtReferenciaProductoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtIdClienteVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtIdEmpleadoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateVentas)
                    .addComponent(btnSelectVentas)
                    .addComponent(btnUpdateVentas)
                    .addComponent(btnDeleteVentas))
                .addContainerGap())
        );

        listaEmpleados.addTab("Ventas", jPanel5);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Producto 1", "Producto 2", "Producto 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaEmpleado.setViewportView(jList1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listaEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listaEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        listaEmpleados.addTab("Lista Empleados", jPanel7);

        jLabel28.setText("Id cliente");

        txtIdFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdFacturacionActionPerformed(evt);
            }
        });

        tablaFacturacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Referencia", "Cantidad", "Precio unitario", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaFacturacion);

        jLabel29.setText("TOTAL");

        txtTotalFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalFacturaActionPerformed(evt);
            }
        });

        btnCrearFactura.setText("Generar Factura");
        btnCrearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(txtTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel29))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel28)
                        .addGap(35, 35, 35)
                        .addComponent(txtIdFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnCrearFactura)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtIdFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        listaEmpleados.addTab("Facturación", jPanel8);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sol Fitness");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
            .addComponent(listaEmpleados)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateVentasActionPerformed

    private void btnCreateEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEmpleadoActionPerformed
        //JOptionPane.showMessageDialog(this, "Esto es una prueba desde crear empleado");
        String id = txtIdEmpleado.getText();
        String nombre = txtNombreEmpleado.getText();
        String apellido = txtApellidoEmpleado.getText();
        String cargo = txtCargoEmpleado.getText();
        String correoElectronico = txtCorreoElectronicoEmpleado.getText();
        String documentoIdentidad = txtDocumentoIdentidadEmpleado.getText();
        
        if(nombre.equals("") || apellido.equals("") || cargo.equals("") || correoElectronico.equals("") || documentoIdentidad.equals("")){
            JOptionPane.showMessageDialog(this, "Complete todos los campos");
        
        }else{
            clsEmpleado empleado = new clsEmpleado(cargo, id, nombre, apellido, documentoIdentidad, correoElectronico);
            ctlEmpleado.createEmpleado(empleado);
            //empleadoObjectList.add(empleado);
            this.FillJlistEmpleado();
            JOptionPane.showMessageDialog(this, "Registro exitoso");
        }
    }//GEN-LAST:event_btnCreateEmpleadoActionPerformed

    private void btnCreateproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateproductoActionPerformed
        // TODO add your handling code here: 
        try{
        String referencia = txtReferenciaProducto.getText();
        String nombre = txtNombreProducto.getText();
        String talla = cbTallaProducto.getSelectedItem().toString();
        String color = cbColorProducto.getSelectedItem().toString();
        int precio = Integer.parseInt(txtPrecioProducto.getText());
        
        if(referencia.equals("") || nombre.equals("")){
          JOptionPane.showMessageDialog(this, "Completa todos los campos");  
        
        }else{
            clsProducto producto = new clsProducto(referencia, nombre, talla, color, precio);
            ctlProducto.createProducto(producto);
            //productoObjectList.add(producto);
            this.clearProductoFields();
            this.FillJlist();
            JOptionPane.showMessageDialog(this, "Registro exitoso");
        } 
        }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Por favor ingrese un precio valido");
        }  
    }//GEN-LAST:event_btnCreateproductoActionPerformed

    private void btnSelectProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectProductoActionPerformed
        String referencia = txtReferenciaProducto.getText();
        clsProducto producto = ctlProducto.selectProducto(referencia);
        
        if(producto == null){
            JOptionPane.showMessageDialog(this, "Referencia no encontrada");
        }else{
            txtNombreProducto.setText(producto.getNombre());
            cbTallaProducto.setSelectedItem(producto.getTalla());
            cbColorProducto.setSelectedItem(producto.getColor());
            txtPrecioProducto.setText(producto.getPrecio() + "");
            
        }
    }//GEN-LAST:event_btnSelectProductoActionPerformed

    private void btnUpadteProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpadteProductoActionPerformed
       try{
            String referencia = txtReferenciaProducto.getText();
            String nombre = txtNombreProducto.getText();
            String talla = cbTallaProducto.getSelectedItem().toString();
            String color = cbColorProducto.getSelectedItem().toString();
            int precio = Integer.parseInt(txtPrecioProducto.getText());
            clsProducto producto = new clsProducto(referencia, nombre, talla, color, precio);     
            boolean response = ctlProducto.updateProducto(producto);
            if(response){
                JOptionPane.showMessageDialog(this, "Actualización exitosa");
            }else{
                JOptionPane.showMessageDialog(this, "Error en la actualización");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Tienes que buscar el registro para actualizar");
        }
    }//GEN-LAST:event_btnUpadteProductoActionPerformed

    private void btnDeleteProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductoActionPerformed
        String referencia = txtReferenciaProducto.getText();
        if (referencia.equals("")){
            JOptionPane.showMessageDialog(this, "Aún no ha buscado un producto");      
        }else{
            try{
                clsProducto producto = new clsProducto(referencia); 
                boolean removed = ctlProducto.deleteProducto(producto); 
                if (removed){
                    this.FillJlist();
                    this.clearProductoFields();
                    JOptionPane.showMessageDialog(this, "Registro eliminado"); 
                }else{
                    JOptionPane.showMessageDialog(this, "ha ocurrido un error durante la eliminación del producto"); 
                }
                
            }catch(Exception e){
                System.out.println(e.toString());
                JOptionPane.showMessageDialog(this, "busque un producto (por referencia) que desee eliminar y vuelva a intentarlo"); 
                
            }
        }
    }//GEN-LAST:event_btnDeleteProductoActionPerformed

        private void FillJlist(){
        DefaultListModel model = new DefaultListModel();
        int index = 0;
        for (clsProducto producto : productoObjectList) {
            String data = producto.getNombre() + " - " + producto.getReferencia() + " - " + producto.getPrecio() + " - " + producto.getTalla() + " - " + producto.getColor();
            model.add(index, data);
            index++;
        }
        listaProductos.setModel(model);
    }

        private void clearProductoFields(){
            txtReferenciaProducto.setText("");
            txtNombreProducto.setText("");
            cbTallaProducto.setSelectedIndex(0);
            cbColorProducto.setSelectedIndex(0);
            txtPrecioProducto.setText("");
            
        } 
        
    private void btnSelectEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectEmpleadoActionPerformed
        String id = txtIdEmpleado.getText();
        clsEmpleado empleado = ctlEmpleado.selectEmpleado(id);
        if(empleado == null){
            JOptionPane.showMessageDialog(this, "Id no encontrado");
        }else{
            txtNombreEmpleado.setText(empleado.getNombre());
            txtApellidoEmpleado.setText(empleado.getApellido());
            txtCargoEmpleado.setText(empleado.getCargo());
            txtDocumentoIdentidadEmpleado.setText(empleado.getDocumentoIdentidad());
            txtCorreoElectronicoEmpleado.setText(empleado.getCorreoElectronico());
           
        }
    }//GEN-LAST:event_btnSelectEmpleadoActionPerformed

    private void btnUpdateEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEmpleadoActionPerformed
       try{
            String id = txtIdEmpleado.getText();
            String nombre = txtNombreEmpleado.getText();
            String apellido = txtApellidoEmpleado.getText();
            String cargo = txtApellidoEmpleado.getText();
            String documentoIdentidad = txtDocumentoIdentidadEmpleado.getText();
            String correoElectronico = txtCorreoElectronicoEmpleado.getText();
            clsEmpleado empleado = new clsEmpleado(cargo, id, nombre, apellido, documentoIdentidad, correoElectronico);
            boolean response = ctlEmpleado.updateEmpleado(empleado);
            if(response){
                JOptionPane.showMessageDialog(this, "Actualización exitosa");
            }else{
                JOptionPane.showMessageDialog(this, "Error en la actualización");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Tienes que buscar el registro para actualizar");
        }
    }//GEN-LAST:event_btnUpdateEmpleadoActionPerformed

    private void btnDeleteEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmpleadoActionPerformed
        String id = txtIdEmpleado.getText();
        if (id.equals("")){
            JOptionPane.showMessageDialog(this, "Aún no ha buscado un empleado");      
        }else{
            try{
                clsEmpleado empleado = new clsEmpleado(id);
                boolean removed = ctlEmpleado.deleteEmpleado(empleado); 
                if (removed){
                    this.FillJlistEmpleado();
                    JOptionPane.showMessageDialog(this, "Registro eliminado"); 
                }else{
                    JOptionPane.showMessageDialog(this, "ha ocurrido un error durante la eliminación del empleado"); 
                }
                
            }catch(Exception e){
                System.out.println(e.toString());
                JOptionPane.showMessageDialog(this, "busque un empleado (por Id) que desee eliminar y vuelva a intentarlo"); 
                
            }
        }
    }//GEN-LAST:event_btnDeleteEmpleadoActionPerformed

    private void txtIdFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdFacturacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdFacturacionActionPerformed

    private void txtTotalFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalFacturaActionPerformed

    private void btnCrearFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearFacturaActionPerformed
        String id = txtIdFacturacion.getText();

        JFrame f;
        String data[][]={
            {"101","Amit","670000"},
            {"102","Jai","780000"},
            {"101","Sachin","700000"}
        };
        String column[]={"ID","NAME","SALARY"};
        
    }//GEN-LAST:event_btnCrearFacturaActionPerformed
         
        private void FillJlistEmpleado(){
        DefaultListModel model = new DefaultListModel();
        int index = 0;
        for (clsEmpleado empleado : empleadoObjectList) {
            String data = empleado.getId() + " - " + empleado.getNombre() + " - " + empleado.getApellido()+ " - " + empleado.getCargo()+ " - " + empleado.getDocumentoIdentidad()+ " - " + empleado.getCorreoElectronico();
            model.add(index, data);
            index++;
        }
        jList1.setModel(model);
    }
        
        
    /**
     * @param args the command line arguments111
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSolFitness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSolFitness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSolFitness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSolFitness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSolFitness().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearFactura;
    private javax.swing.JButton btnCreateCliente;
    private javax.swing.JButton btnCreateEmpleado;
    private javax.swing.JButton btnCreateVentas;
    private javax.swing.JButton btnCreateproducto;
    private javax.swing.JButton btnDeleteCliente;
    private javax.swing.JButton btnDeleteEmpleado;
    private javax.swing.JButton btnDeleteProducto;
    private javax.swing.JButton btnDeleteVentas;
    private javax.swing.JButton btnSelectCliente;
    private javax.swing.JButton btnSelectEmpleado;
    private javax.swing.JButton btnSelectProducto;
    private javax.swing.JButton btnSelectVentas;
    private javax.swing.JButton btnUpadteProducto;
    private javax.swing.JButton btnUpdateCliente;
    private javax.swing.JButton btnUpdateEmpleado;
    private javax.swing.JButton btnUpdateVentas;
    private javax.swing.JComboBox<String> cbColorProducto;
    private javax.swing.JComboBox<String> cbTallaProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JScrollPane listaEmpleado;
    private javax.swing.JTabbedPane listaEmpleados;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JTable tablaFacturacion;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JTextField txtApellidoEmpleado;
    private javax.swing.JTextField txtCantidadVentas;
    private javax.swing.JTextField txtCargoEmpleado;
    private javax.swing.JTextField txtContraseñaAcceso;
    private javax.swing.JTextField txtCorreoElectronicoCliente;
    private javax.swing.JTextField txtCorreoElectronicoEmpleado;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtDocumentoIdentidadCliente;
    private javax.swing.JTextField txtDocumentoIdentidadEmpleado;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdClienteVentas;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtIdEmpleadoVentas;
    private javax.swing.JTextField txtIdFacturacion;
    private javax.swing.JTextField txtIdVentas;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtReferenciaProducto;
    private javax.swing.JTextField txtReferenciaProductoVentas;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtTotalFactura;
    private javax.swing.JTextField txtUsuarioAcesso;
    // End of variables declaration//GEN-END:variables
}